export const clients = [
  {
    id: 1,
    nom: "Pierre Martin",
    entreprise: "Martin Commerce",
    secteur: "Commerce",
    email: "pierre.martin@martincommerce.fr",
    telephone: "06 12 34 56 78",
    statut: "actif",
    mrr: 150,
    installation: 2000,
    dateDebut: "2024-01-15",
    avancement: 100,
    notes: "Premier client. Très satisfait. A récupéré 23 000€ de devis oubliés en 3 mois.",
    automatisations: ["Relances devis automatiques", "Ressaisie comptabilité", "Dashboard rentabilité"],
    prochainAction: "Renouvellement 12 mois",
    linkedin: "https://linkedin.com/in/pierre-martin",
    tags: ["référence", "commerce", "relances"]
  },
  {
    id: 2,
    nom: "Jacques Moreau",
    entreprise: "Moreau Logistique",
    secteur: "Logistique",
    email: "j.moreau@moreau-logistique.fr",
    telephone: "06 23 45 67 89",
    statut: "actif",
    mrr: 1700,
    installation: 9000,
    dateDebut: "2024-02-01",
    avancement: 85,
    notes: "120 salariés. DSI Thomas Petit validé techniquement. Très exigeant mais satisfait.",
    automatisations: ["Relances commerciaux", "Ressaisie compta", "Dashboard RH", "Accès Supabase DSI"],
    prochainAction: "Livraison complète semaine prochaine",
    linkedin: "https://linkedin.com/in/jacques-moreau",
    tags: ["logistique", "grande-entreprise", "dsi"]
  },
  {
    id: 3,
    nom: "Bernard Dupuis",
    entreprise: "Bernard & Associés BTP",
    secteur: "BTP",
    email: "bernard@bernard-btp.fr",
    telephone: "06 34 56 78 90",
    statut: "actif",
    mrr: 3000,
    installation: 15000,
    dateDebut: "2024-02-15",
    avancement: 60,
    notes: "80 salariés, 12 chantiers actifs. App chefs de chantier en cours. Très dur à convaincre mais excellent client.",
    automatisations: ["App chefs de chantier", "Suivi chantiers temps réel", "Relances devis", "Facturation auto"],
    prochainAction: "Démo partielle dans 2 semaines",
    linkedin: "https://linkedin.com/in/bernard-dupuis",
    tags: ["btp", "chantiers", "app-mobile"]
  },
  {
    id: 4,
    nom: "Christophe Renard",
    entreprise: "Renard Immobilier",
    secteur: "Immobilier",
    email: "c.renard@renard-immo.fr",
    telephone: "06 45 67 89 01",
    statut: "actif",
    mrr: 4000,
    installation: 25000,
    dateDebut: "2024-03-01",
    avancement: 40,
    notes: "200 salariés. Voice bot en production. Très exigeant. A présenté 4 nouveaux prospects après la démo.",
    automatisations: ["Voice bot IA", "Relances acquéreurs", "Facturation programmes", "Dashboard promoteur"],
    prochainAction: "Livraison voice bot bilingue",
    linkedin: "https://linkedin.com/in/christophe-renard",
    tags: ["immobilier", "voice-bot", "grands-comptes"]
  },
  {
    id: 5,
    nom: "Michel Dupré",
    entreprise: "Dupré Transport",
    secteur: "Transport",
    email: "m.dupre@dupre-transport.fr",
    telephone: "06 56 78 90 12",
    statut: "en-cours",
    mrr: 3500,
    installation: 20000,
    dateDebut: "2024-03-15",
    avancement: 10,
    notes: "150 salariés, 47 chauffeurs. App tracking chauffeurs en développement. Très sympa, réseau de 10 transporteurs.",
    automatisations: ["Tracking chauffeurs temps réel", "Voice bot appels entrants", "Alertes retards clients", "Dashboard logistics"],
    prochainAction: "Démo partielle tracking dans 1 mois",
    linkedin: "https://linkedin.com/in/michel-dupre",
    tags: ["transport", "tracking", "voice-bot"]
  }
]

export const stats = {
  mrr_total: 12350,
  installation_total: 71000,
  clients_actifs: 4,
  clients_en_cours: 1,
  prospects: 6,
  taux_satisfaction: 98
}
